sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
# matrix:
#   allow_failures:
    - rust: nightly
script: |
  cargo build &&
  cargo test  tests::main &&
  cargo test  old_and_new
  # cargo doc

notifications:
  email:
    on_success: never