sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
matrix:
  allow_failures:
    - rust: nightly
#     - rust: stable
#     - rust: beta
script: |
  cargo build &&
  cargo test test &&
  cargo test src/lib.rs &&
  cargo test src/inner.rs
  

notifications:
  email:
    on_success: never